---
version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    container_name: zookeeper
    hostname: zookeeper
    deploy:
      restart_policy:
        delay: 5s
        window: 10s
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.0
    hostname: broker
    container_name: broker
    ports:
      - "127.0.0.1:9092:9092"
    depends_on:
      - zookeeper
    deploy:
      restart_policy:
        delay: 5s
        window: 10s
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  schemaregistry:
    image: confluentinc/cp-schema-registry:7.0.0
    hostname: schemaregistry
    container_name: schemaregistry
    deploy:
      restart_policy:
        delay: 5s
        window: 10s
    depends_on:
      - zookeeper
      - broker
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
    ports:
      - "127.0.0.1:8085:8085"
  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    deploy:
      restart_policy:
        delay: 5s
        window: 10s
    hostname: kowl
    container_name: kowl
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - broker
      - schemaregistry
    environment:
      KAFKA_BROKERS: broker:29092
      KAFKA_SCHEMAREGISTRY_ENABLED: true
      KAFKA_SCHEMAREGISTRY_URLS: http://schemaregistry:8085
